// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitAPeople(msg string) People {
	meta := NewMeta()
	message := NewMessage(msg, meta)
	mouth := NewMouth(message)
	hand := NewHand(message)
	people := NewPeople(mouth, hand)
	return people
}
